services:
  glucohealth-backend:
    build:
      context: .
      args:
        - APP_PORT=${APP_PORT}
    depends_on:
      - glucohealth-database
    ports:
      - target: ${APP_PORT}
        published: ${APP_PORT}
    env_file:
      - ./.env
  glucohealth-database:
    image: postgres:16.2
    restart: always
    ports:
      - target: ${DATABASE_PORT}
        published: ${DATABASE_PORT}
    volumes:
      - glucohealth-database:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
volumes:
  glucohealth-database: